style.fill: transparent
direction: down

start: Start
done: Working code

first: First attempt
second: Second attempt

start -> done: do it
start -> first: do it
first -> second: use the latest syntax
second -> done: no, the 2026 syntax
