services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: zou-minowa-portfolio-dev
    user: node
    ports:
      - "4321:4321"
    volumes:
      - ..:/workspaces/zou-minowa-portfolio:cached
      - ../.gitconfig:/home/node/.gitconfig
    command: sleep infinity
